---

- name: Snapd | Remove snapd package
  apt: name=snapd state=absent purge=yes

- name: Snapd | Purge snapd directories
  block:
    - name: Snapd | Remove snapd directories /var/lib/snapd
      import_tasks: directory-purge.yml
      vars:
        target_directory_path: /var/lib/snapd

    - name: Snapd | Remove snapd directories /var/cache/snapd
      import_tasks: directory-purge.yml
      vars:
        target_directory_path: /var/cache/snapd
