---
# from https://github.com/do-community/ansible-playbooks/blob/master/docker_ubuntu1804/playbook.yml
- name: Docker | Prerequisites
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Docker | Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker | Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Docker | Remove default docker package
  apt: name=docker update_cache=yes state=absent

- name: Docker | Install docker-ce
  apt: name=docker-ce update_cache=yes state=latest

- name: Docker | Enable and start
  service:
    name: docker
    state: started
    enabled: yes
